### ISSUE TITLE
Allow users to set the icon of their own project as an icon

### ISSUE THREAD

**Issue by 439bananas** [Ryavell/VisualStudioDiscordRPC#11]
This could possibly be up for debate as to where the icon should be stored, etc, but it could be pretty sweet to allow the user to set an icon on a per-project basis, and it would show in the rich presence status.

**Comment by cabiste69** [comment]
I don't think this is possible since all the images are saved in the discord developer page for this application.

**Comment by Ryavell** [comment]
As a solution for adding your own icons, I can add the ability to specify your own Discord application, where your own icons for projects and file extensions will be stored. Then the responsibility for assigning assets names and adding the assets themselves will be on the creator of the Discord application.

**Comment by Ryavell** [comment]
Available in 1.4.5 version.
Settings -> General -> Advanced
Then you need to specify the ID of your Discord application.
**Important:** the names of assets in the application must match the names from the [extensions_assets_map.json](https://github.com/Ryavell/VisualStudioDiscordRPC/blob/main/VisualStudioDiscordRPC.Shared/extensions_assets_map.json) file
