### ISSUE TITLE
Discord doesn't recognize Visual Studio

### ISSUE THREAD

**Issue by Cryzuz** [Ryavell/VisualStudioDiscordRPC#12]
I have reinstalled your Plugin several times but I can't make it work.
There is the Discord Rich Presence Plugin in the Extensions Tab so it is installed but Discord doesn't recognize it somehow.

**Comment by Ryavell** [comment]
Have you tried restarting Visual Studio after installing the plugin? The plugin may not initialize if it is not done. Sometimes the plugin may not "see" the launch of Visual Studio, but when opening files it starts working.
In addition, can you attach your version of Visual Studio? And, just in case, the version of the installed plugin.

**Comment by Ryavell** [comment]
What about opening a file? Discord also doesn't react?
Can you also attach this file?
%AppData%\Microsoft\VisualStudio\<your_version>\ActivityLog.xml 
There should be an error log. It might help me.

**Comment by Cryzuz** [comment]
No Discord doesn't react, nothing is shown.
I don't have any error log there, only an activity log.

Activity Log:
[ActivityLog.zip](https://github.com/Ryavell/VisualStudioDiscordRPC/files/8981679/ActivityLog.zip)

**Comment by Ryavell** [comment]
I didn't find any problems in the ActivityLog.  
Could you check something else: did the "Visual Studio Discord RPC" option appear in the "Extensions" menu?
I also made a build with some changes. You can also install it and check it again.
[VisualStudioDiscordRPC.Dev17_Debug.zip](https://github.com/Ryavell/VisualStudioDiscordRPC/files/8984621/VisualStudioDiscordRPC.Dev17_Debug.zip)

Thank you for helping me with testing the extension.

**Comment by Cryzuz** [comment]
I have installed the build you have sent me but again no reaction from Discord
Yes I see the "Visual Studio Discord RPC" option in the Extensions menu.

When I click on it, the settings window pop ups:
![image](https://user-images.githubusercontent.com/8808157/175775129-a9304dd0-511f-456f-88c5-22a786d63d04.png)

**Comment by Ryavell** [comment]
Very interesting . The plugin is installed and initialized successfully. So there is some problem with the document change event.
Can you install this version with diagnostic MessageBox?
[VisualStudioDiscordRPC.Dev17.zip](https://github.com/Ryavell/VisualStudioDiscordRPC/files/8985152/VisualStudioDiscordRPC.Dev17.zip)

I'm sorry for asking you to test this extension so much.

**Comment by Cryzuz** [comment]
Sure. When I switch between Tabs it says "Window changed to: Consumables".
In VS the Plugin recognizes the .cs Sheets but somehow it doesnt get shown in Discord.

**Comment by Ryavell** [comment]
Have you checked the Activity Status settings in discord?
I'm already running out of options, what could be the problem. Everything looks workable, but no.
![image](https://user-images.githubusercontent.com/55898777/175785605-afce055d-18c2-4349-a8ac-e22ce1cb1b27.png)

**Comment by Cryzuz** [comment]
It's activated.
Am I the only one with the problem? If its only me I have to look up for a solution myself.

**Comment by Ryavell** [comment]
On my other machine, the extension works stably.
It also works "stably" for you, because the tab change event is triggered and immediately after that there should be an update of the Discord RPC status.
Still, it seems to me that the problem is not in the extension.
I'll leave the question open. Perhaps someone else will report such a problem.

**Comment by Cryzuz** [comment]
I have reinstalled Discord and suddenly it works.
Thanks for the support, if anyone has the same problem, this is the solution then :)

**Comment by Cryzuz** [comment]
Have found the issue, as soon as you start Discord as admin, it doesn't work anymore.
Then you have to delete Discord and install it again. :)

**Comment by berserk-dev** [comment]
Can confirm that running discord as admin causes this, however, I did not need to reinstall.
Running VS2022 as admin seems to fix the issue.

**Comment by Ryavell** [comment]
I have another variation of this bug, which I have not yet learned how to reproduce: even if I do not run the discord with administrator rights, the discord does not recognize the open Visual Studio.
**Solved by restarting the Discord.**
How to solve this on the extension side: I don't have any options yet.
