### ISSUE TITLE
The repository button doesn't seem to function

### ISSUE THREAD

**Issue by bananaturtlesandwich** [Ryavell/VisualStudioDiscordRPC#13]
When the option is checked in the extension menu and the button is clicked it doesn't seem to bring up anything
![](https://user-images.githubusercontent.com/71292624/175811654-6f70d6a7-8ae6-4c1a-b862-0960e89c0c73.png)

**Comment by Ryavell** [comment]
If you click on this button yourself, then nothing will happen.
This will work if another Discord user clicks on the button.
This is how Discord buttons work.

Try asking someone to click on this button :)
This should work.

Let me know if it doesn't work in this case.

**Comment by bananaturtlesandwich** [comment]
Ah ok I just misunderstood the feature then. Thank you for the quick response!
