### ISSUE TITLE
The 'VisualStudioDiscordRPCPackage' package did not load correctly

### ISSUE THREAD

**Issue by JoshuaMaitland** [Ryavell/VisualStudioDiscordRPC#16]
After I installed that extension on Visual Studio 2022, I get this message popped up every time telling me that it did not load correctly. And I'm not so sure how I would fix it!! (Username has been removed). The version that I'm using is v1.3.3
![devenv_2022-07-06_20-17-34](https://user-images.githubusercontent.com/46503276/177628799-ef36dc7f-b2b6-409f-a738-5177f980da86.png)

**Comment by labalityowo** [comment]
Also got the issue here, what I found in the log file

```
<entry>
    <record>365</record>
    <time>2022/07/07 04:57:48.208</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [VisualStudioDiscordRPCPackage]Source: &apos;VisualStudioDiscordRPC.Dev17&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=17.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=17.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Threading, Version=17.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at VisualStudioDiscordRPC.Shared.VisualStudioDiscordRPCPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__76.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{5CD3D640-3D33-45EA-8C5B-6DE981FF9900}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>
  ```

**Comment by sametguzeldev** [comment]
> Can you attach this file here?


I have the same issue.
Here is the file.
[ActivityLog.zip](https://github.com/Ryavell/VisualStudioDiscordRPC/files/9062205/ActivityLog.zip)

**Comment by sametguzeldev** [comment]
![image](https://user-images.githubusercontent.com/6827857/177741638-1b691f43-3c5c-4368-8b81-bd4f2ed555a3.png)

**Comment by Ryavell** [comment]
Maybe something with an automated build in GitHub Actions.
I built .vsix manually. Can you try installing this one?

[VisualStudioDiscordRPC.Dev17.zip](https://github.com/Ryavell/VisualStudioDiscordRPC/files/9062685/VisualStudioDiscordRPC.Dev17.zip)

**Comment by sametguzeldev** [comment]
> Maybe something with an automated build in GitHub Actions. I built .vsix manually. Can you try installing this one?
> 
> [VisualStudioDiscordRPC.Dev17.zip](https://github.com/Ryavell/VisualStudioDiscordRPC/files/9062685/VisualStudioDiscordRPC.Dev17.zip)

Still the same error.
![image](https://user-images.githubusercontent.com/6827857/177753723-e56405c3-6d74-42a6-b0aa-4fde6ac45089.png)

**Comment by sametguzeldev** [comment]
I downloaded the older version [Discord RPC for Visual Studio v1.3.1](https://github.com/Ryavell/VisualStudioDiscordRPC/releases/tag/v1.3.1) which is working btw. Seems to be something in the new version.

**Comment by sametguzeldev** [comment]
> > Maybe something with an automated build in GitHub Actions. I built .vsix manually. Can you try installing this one?
> > [VisualStudioDiscordRPC.Dev17.zip](https://github.com/Ryavell/VisualStudioDiscordRPC/files/9062685/VisualStudioDiscordRPC.Dev17.zip)
> 
> Tried that and it doesn't work. Still the same issue. But I attached the ActivityLog anyway. [ActivityLog.zip](https://github.com/Ryavell/VisualStudioDiscordRPC/files/9062791/ActivityLog.zip)

Can you try the older version which is [Discord RPC for Visual Studio v1.3.1](https://github.com/Ryavell/VisualStudioDiscordRPC/releases/tag/v1.3.1) and see if it works for you?

**Comment by sametguzeldev** [comment]
> Maybe something with an automated build in GitHub Actions. I built .vsix manually. Can you try installing this one?
> 
> [VisualStudioDiscordRPC.Dev17.zip](https://github.com/Ryavell/VisualStudioDiscordRPC/files/9062685/VisualStudioDiscordRPC.Dev17.zip)

I've checked the commits and saw that there are libraries added to the project. Maybe they are depending on that version or something?

**Comment by sametguzeldev** [comment]
> > > > Maybe something with an automated build in GitHub Actions. I built .vsix manually. Can you try installing this one?
> > > > [VisualStudioDiscordRPC.Dev17.zip](https://github.com/Ryavell/VisualStudioDiscordRPC/files/9062685/VisualStudioDiscordRPC.Dev17.zip)
> > > 
> > > 
> > > Tried that and it doesn't work. Still the same issue. But I attached the ActivityLog anyway. [ActivityLog.zip](https://github.com/Ryavell/VisualStudioDiscordRPC/files/9062791/ActivityLog.zip)
> > 
> > 
> > Can you try the older version which is [Discord RPC for Visual Studio v1.3.1](https://github.com/Ryavell/VisualStudioDiscordRPC/releases/tag/v1.3.1) and see if it works for you?
> 
> I actually using v1.3.2 and it does works and doesn't show a warning message at all at startup!!

If you click "No" to this pop-up, you will not see the error message anymore. You need to reinstall to see that error message again.
![image](https://user-images.githubusercontent.com/6827857/177756899-f0110f10-59fc-4864-992b-9c35c372b5bd.png)

**Comment by Ryavell** [comment]
Hello, guy!
Recently, such error messages have started to appear frequently again. 
Do you have such a problem?

**Comment by Ryavell** [comment]
The problem is in different versions of Visual Studio and packages in the extension.
**Solution: to install a newer version of Visual Studio.**
