### ISSUE TITLE
Excluding some projects for display

### ISSUE THREAD

**Issue by Ryavell** [Ryavell/VisualStudioDiscordRPC#17]
Some projects should not be displayed.
It need to add such a list of projects somewhere in the settings window.

**Comment by ohkriss** [comment]
A feature that allows you to not display your current project on demand would be nice yea, instead it will display "Working on something secret" or a custom message?

**Comment by Ryavell** [comment]
A custom message and a hard-coded message is almost the same in implementation.
I am more inclined to a hard-coded message, because otherwise the user will be able to write absolutely any message (even if it has nothing to do with "secrecy").
But I'll think about it.

**Comment by stackwalking** [comment]
> 

I can work on a secret option and make a PR, if you haven't already

**Comment by Ryavell** [comment]
It would be nice if you help with this feature. :)

**Comment by Ryavell** [comment]
@stackwalking How about the feature?

**Comment by Ryavell** [comment]
Implemented by [this commit](https://github.com/Ryavell/VisualStudioDiscordRPC/commit/44730d04f705df21578578843554c3e9848b33e8)
