### ISSUE TITLE
VisualStudioDiscordPRCPackage did not load correctly

### ISSUE THREAD

**Issue by Insigne** [Ryavell/VisualStudioDiscordRPC#18]
Hi!
So, for some reason my VS doesn't want to load the extension in any way and i'm not sure why.
I didn't change anything in my VS, and I haven't opened it for days.

Image:
![image](https://user-images.githubusercontent.com/53184703/188156128-d1bbfbb1-c572-4115-b817-941cd3250712.png)

**Comment by Ryavell** [comment]
Hi. 
I think, this issue is duplicate of #16.
I need to downgrade some packages versions.

**Comment by Insigne** [comment]
Oh damn it is a duplicate, sorry.
Thanks.

**Comment by Ryavell** [comment]
Yes. It's duplicate. But it's good that you reported again.
I recently upgraded the versions of the some packages, and apparently this error has appeared again.
Try to install version 1.4.3 after a while and check if the extension is working.
