### ISSUE TITLE
Feature Request: Do Not Reset Elapsed Time on File Change

### ISSUE THREAD

**Issue by EthanC** [Ryavell/VisualStudioDiscordRPC#2]
A toggleable option to prevent the elapsed time from resetting each time a different file is opened would be appreciated. This would serve as a way to display the total time that the Solution has been worked on, rather than the individual file.

**Comment by Ryavell** [comment]
I think it is possible to make a flexible adjustment of this timer.
1) The ability to turn off the timer altogether;
2) Timer counts the running time for:
- file;
- project;
- solution;
- the current method being edited (this is expected in the future).

**Comment by Ryavell** [comment]
Finally this feature is added to the settings menu and it works.
