### ISSUE TITLE
Solution Names are prepended by "Project"

### ISSUE THREAD

**Issue by adanvdo** [Ryavell/VisualStudioDiscordRPC#24]
If you choose to display the Visual Studio Solution name, it is prepended by "Project" in the user's profile. 

In the example below, I have chosen to display the Solution followed by the Project. As you can see, it lists them both as projects. 

![image](https://user-images.githubusercontent.com/26498008/190838520-02d34680-0fc7-4e1d-a924-099e651c2cdc.png)

![image](https://user-images.githubusercontent.com/26498008/190838535-6d1c5aeb-9c16-4875-84d5-6b2295f81fbc.png)

**Comment by Ryavell** [comment]
Yes, I know about it. Thank you for creating the Issue. There is no translation for 'Solution' right now. Therefore, it has been replaced by a translation for 'Project' for now.

**Comment by Ryavell** [comment]
Available in 1.4.5 version
