### ISSUE TITLE
Displaying debug status and debugging file

### ISSUE THREAD

**Issue by R3uan3** [Ryavell/VisualStudioDiscordRPC#25]
When you have multiples projects running it shows the first project you opened in your profile and the 
others under the tab 'Activity'.

Would like to ask if is possible to continually replace the project under your profile according 
to the most recent project edited.

Also, if possible to display in the title when you be debugging a file.

**Comment by Ryavell** [comment]
It seems unlikely that this can be done.
The Discord client API does not allow access to changing the display order of Activities.

**Comment by R3uan3** [comment]
I see, and about displaying when you're debugging a file?

**Comment by Ryavell** [comment]
I think it's possible.
