### ISSUE TITLE
(suggestion) having a total time timer which doesn't get reset when changing files

### ISSUE THREAD

**Issue by Noscka** [Ryavell/VisualStudioDiscordRPC#27]
currently when you switch from one file to another inside the project, it resets the timer on the RPC. it would be cool if there was a separate timer or if the currently existing timer would not reset when changing files.

**Comment by Ryavell** [comment]
It seems to me that this feature has already been implemented.
Select the timer mode in settings window.

Within files - the timer time is reset when switching from one file to another.
Within projects - the timer time is reset when switching from one project to another.
Within solutions - the timer time is reset when switching from one solution to another.

Or do you mean something else?

**Comment by Noscka** [comment]
this is what I was looking for. thank you.
