### ISSUE TITLE
Doesn't change my status

### ISSUE THREAD

**Issue by xuanhuongtrinh76** [Ryavell/VisualStudioDiscordRPC#28]
Not sure what I'm doing wrong, but I'm using Visual Studio 2022 and have the 2022 extension installed, but my status isn't changing in discord.

**Comment by Ryavell** [comment]
Try to find the answer in issue #12. There was a similar problem that was solved by restarting/reinstalling the discord

**Comment by Ryavell** [comment]
@xuanhuongtrinh76
Did anything help from that issue?
