### ISSUE TITLE
The timer is reset when switching to any window

### ISSUE THREAD

**Issue by Ryavell** [Ryavell/VisualStudioDiscordRPC#3]
When switching focus to any window in Visual Studio, even if it is not associated with open documents, or when running Debug (loss of focus from the window), the timer is reset, while the document tab has not changed.

**Comment by hootanht** [comment]
switch to another file is reset the timer, please make the ability to control it

**Comment by Ryavell** [comment]
Feature #2 introduces this ability, you can choose a trigger when you need to reset the timer (file, project, solution) or disable timer.

**Comment by hootanht** [comment]
> Feature #2 introduces this ability, you can choose a trigger when you need to reset the timer (file, project, solution) or disable timer.

Waiting for this feature

**Comment by Ryavell** [comment]
A new update is expected soon. There were some problems with uploading the extension into the Visual Studio marketplace. Probably the release of the new version will appear earlier here - in this repository. But I would like to upload extension in the VS marketplace at the same time.

**Comment by hootanht** [comment]
do we have #2 in this update?

**Comment by Ryavell** [comment]
> do we have #2 in this update?

Of course, yes
