### ISSUE TITLE
Implement selective display of links for repositories. 

### ISSUE THREAD

**Issue by d7chelovechek** [Ryavell/VisualStudioDiscordRPC#31]
For example, you can allow links to GitHub, but not to GitLab.

**Comment by Ryavell** [comment]
It seems to me that this will create maintenance problems in the future. There can be a large number of specific Git repository hosting services (it is clear that GitHub and GitLab are the most popular).

I would suggest just adding a "Show/hide for current solution" option.

**Comment by d7chelovechek** [comment]
How do you imagine this setting? Every time go to the extension settings and turn on / off the checkbox?

**Comment by Ryavell** [comment]
When you check the checkbox in the settings, it will be saved for which repository it was enabled. It won't need to be turned on every time.
