### ISSUE TITLE
Implement the ability to not display links of private repositories.

### ISSUE THREAD

**Issue by d7chelovechek** [Ryavell/VisualStudioDiscordRPC#32]

**Comment by Ryavell** [comment]
Unfortunately, the LibGit library does not provide such functionality. In addition, the "privacy" of the repository depends on the specific repository hosting service. 

I also suggest, as in issue #31, just add the option "Show/hide for the current solution"

**Comment by d7chelovechek** [comment]
You can send a request to the URL of the repository, if you get 404, then the repository is hidden.

**Comment by Ryavell** [comment]
Nice hack!
But do all services respond this way when accessing a private repository?
In a good way, it need to use the API of these services to check the privacy of the repository.

**Comment by Ryavell** [comment]
I'm also not sure about the rest of the services, so I wouldn't want to rely solely on the response code from the service. It doesn't seem too reliable to me.
I continue to insist on a button in the settings that marks the current open repository as private. It's easier to implement and more flexible.

**Comment by Ryavell** [comment]
Now this option is implemented in 1.5.1 version.

**Comment by d7chelovechek** [comment]
Well done!
