### ISSUE TITLE
Support for Discord PTB?

### ISSUE THREAD

**Issue by javedbartlett** [Ryavell/VisualStudioDiscordRPC#35]
I'm using Discord and Discord PTB. Rich Presence shows up on regular discord, but not if I'm only running the PTB version. Is there a way to add support for this?

Thanks

**Comment by Ryavell** [comment]
Hi!

This extension should work with any application that supports Discord Rich Presence, but I haven't specifically checked for stability with Discord PTB. 

At first glance, it seems to me that this is not an extension problem. It just displays the state of Visual Studio.

To interact with Discord, I use the [Third-Party C# implementation of Discord Rich Presence](https://github.com/Lachee/discord-rpc-csharp/).
Maybe there is no support for Discord PTB.

**Comment by javedbartlett** [comment]
Gotcha. I've tried a bunch of different things, but it just doesn't work with PTB. It works fine with the regular discord client though. Discord PTB has experimental features for better screen sharing so I tend to use that instead :(
