### ISSUE TITLE
LiveShare integration

### ISSUE THREAD

**Issue by Ryavell** [Ryavell/VisualStudioDiscordRPC#5]
Is it possible to implement such a feature? LiveShare is also an extension for Visual Studio. How do I get access to installed extensions and their interfaces?

**Comment by mikepattyn** [comment]
I assume LiveShare is for real-time updates to discord?

**Comment by Ryavell** [comment]
Yes. I want to make something like a button to connect to a Live Share session in real time.

**Comment by mikepattyn** [comment]
Ah so the built-in tool by microsoft for online collaboration in the same IDE, you want a button to join the team room?
But what has this got to do with DiscordRPC i wonder. Honestlyy i think that's a extension on its own

**Comment by Ryavell** [comment]
The LiveShare extension itself makes it possible to provide a link to a session that can be sent to a collaborator.
I think it would be convenient to join a LiveShare session by simply clicking on a button in the Discord.
